name: github-UBI8

on:
  pull_request:
    paths-ignore:
    - '**/*.rst'
    - '**/*.md'
    - 'doc/**'
    types: [ opened, reopened, synchronize ]

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  ubi8-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: |
            ghcr.io/sandialabs/opencsp:latest
      - name: Push image
        run: |
          docker push --user "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" ghcr.io/sandialabs/opencsp:latest

  ubi8-ci:
    needs: ubi8-image
    name: ubi8-ci
    runs-on: [ubuntu-latest]
    permissions:
      packages: read
      contents: read
    container: 
      image: ghcr.io/sandialabs/opencsp:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: OpenCSP

      - name: pytest-cov
        working-directory: OpenCSP/opencsp
        run: |
          python3 -m pip install -r ../requirements.txt
          export PYTHONPATH=$PWD/../
          pytest --color=yes -rs -vv --cov=. --cov-report term --cov-config=.coveragerc